### PR TITLE
Corrected boundary, added edgeLengths and seamLengths in SkewPantsHexagon

### PR DESCRIPTION
**Pull request by shabarishch**

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
Does the new skew surface pass `isClosedSurface|

**Comment by shabarishch** [comment]
Sorry, I didn't check that. How should I enumerate SkewPantsSurfaces?  For PantsSurface, we have the allclosed function. Is it okay to only check with the same twist parameter at all curves? Then it is enough to give a vector with all entries the same as a parameter in the enumerate function in object SkewPantsSurface (for each pantssurface coming out of the allclosed function.)

**Comment by siddhartha-gadgil** [comment]
I have added a few cases both in tests and in the worksheet. The skew case
fails for your code. You can try to see what fails in detail.

**Comment by shabarishch** [comment]
Okay, I will do that.

**Comment by siddhartha-gadgil** [comment]
To clarify, being a closed surface means the following 3 things, and I would guess that one of the first two (the simpler ones) fails.

1. Every edge is present with multiplicity (at most) 1.
2. If an edge is present so is its flip.
3. Every edge at a vertex is present in some face. 
4. The link at each vertex is a circle, which means if we look at edges starting at the vertex and rotate clockwise we reach every other edge starting at that vertex.

**Pull request merged**
