### PR TITLE
changed prePareEdgePath for backWardEdgePathMap in quadrangulation and added comments

### PR DESCRIPTION
**Pull request by anotherArka**

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
Minor point,but camelCase should correspond to words. As backward and
prepare are words, they should not become backWard or prePare

regards,
Siddhartha

**Comment by anotherArka** [comment]
I will change it accordingly

**Comment by anotherArka** [comment]
I will push that change in the next commit as it is minor change and the method is a local method.

**Comment by anotherArka** [comment]
Done.

**Pull request merged**
