### PR TITLE
added method to check for closed TwoComplex and TwoComplex with boundary. Soon will add checks for all the methods

### PR DESCRIPTION
**Pull request by anotherArka**

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
Firstly, you mean "closed surface" and "surface with boundary" (everything is a two-complex). More importantly, do you have checks that 

* each edge is in at most one face
* exactly one for the closed case
* at least one of `e`, `e.flip` is in a face for the case with boundary.
* every vertex is in some edge.

**Comment by siddhartha-gadgil** [comment]
Merging to allow others to use this, but need to address the issues

**Comment by anotherArka** [comment]
I thought we are already checking these using Assert

**Comment by anotherArka** [comment]
I will add the conditions shortly

**Pull request merged**
